BOX_IMAGE = "bento/ubuntu-20.04"
VM_NAME = "netology"
NODE_COUNT = 2

Vagrant.configure("2") do |config|
  (1..NODE_COUNT).each do |i|
    config.vm.define "#{VM_NAME}#{i}" do |subconfig|
      subconfig.vm.provider "hyperv"
      subconfig.vm.provider "hyperv" do |h|
        h.linked_clone = true
        h.enable_checkpoints = false
        h.ip_address_timeout = 300
        h.vmname = "#{VM_NAME}#{i}"
      end
      subconfig.vm.box = BOX_IMAGE
      subconfig.vm.hostname = "#{VM_NAME}#{i}"
      subconfig.vm.synced_folder ".", "/vagrant", disabled: true
      subconfig.vm.provision "shell", inline: "sudo apt-get update && sudo apt-get dist-upgrade -y && sudo apt-get autoremove -y && sudo reboot"
    end
  end
end
