 Vagrant.configure("2") do |config|
  config.vm.define "focal" do |subconfig|
    subconfig.vm.box = "bento/ubuntu-20.04"
  end

  config.vm.define "bionic" do |subconfig|
    subconfig.vm.box = "bento/ubuntu-18.04"
  end
 end
