Vagrant.configure("2") do |config|
  config.vm.provider "hyperv"
  config.vm.provider "hyperv" do |h|
    h.linked_clone = true
    h.enable_checkpoints = false
  end
  config.vm.box = "bento/ubuntu-20.04"
  config.vm.network "public_network"
  config.vm.synced_folder ".", "/vagrant", disabled: true
end
